[tool.black]
line-length = 100
target-version = ['py38']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
  )/
)
'''

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 100
multi_line_output = 3
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']

[tool.poetry]
name = "bug-tracker"
license = "MIT"
version = "0.1.0"
readme = "README.md"
description = "Register issues that occured in the projects."
authors = ["Leonid <golani04@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.61.1"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pydantic = {extras = ["dotenv", "email"], version = "^1.6.1"}
uvicorn = "^0.12.1"
requests = "^2.24.0"
SQLAlchemy = "^1.3.22"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = "^20.8b1"
coverage = "^5.4"
flake8 = "^3.8.4"
freezegun = "^0.3.15"
isort = "^5.6.4"
pylint = "^2.6.0"
pytest = "^6.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
