[tool.black]
line-length = 100
target-version = ['py38']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
  )/
)
'''

[tool.poetry]
name = "bug-tracker"
license = "MIT"
version = "0.1.0"
readme = "README.md"
description = "Bug tracking tool to report found bugs in projects."
authors = ["Leonid <golani04@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
python-dotenv = "^0.12.0"
passlib = "^1.7.4"
bcrypt = "^3.2.0"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = {version = "^19.10b0", allow-prereleases = true}
flake8 = "^3.8.4"
freezegun = "^0.3.15"
pytest = "^5.4.3"
pytest-cov = "^2.10.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
